"""empty message

Revision ID: 1346a9f01aa8
Revises: 895b8fb5c847
Create Date: 2019-02-04 11:24:29.971406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1346a9f01aa8'
down_revision = '895b8fb5c847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('dataset', 'is_processing',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'is_processing',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('dataset', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
