"""empty message

Revision ID: 388699aff39e
Revises: 657ec5b7d604
Create Date: 2019-03-11 12:31:29.394592

"""
from alembic import op
# import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388699aff39e'
down_revision = '657ec5b7d604'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('dataset', sa.Column('active', sa.Boolean(),
    # nullable=False))
    # op.add_column('dataset', sa.Column('processing', sa.Boolean(),
    #                                    nullable=False))
    # op.drop_column('dataset', 'is_active')
    # op.drop_column('dataset', 'is_processing')
    # ### end Alembic commands ###
    op.alter_column('dataset', 'is_active', new_column_name='active')
    op.alter_column('dataset', 'is_processing', new_column_name='processing')


def downgrade():
    """Downgrade"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('dataset', sa.Column('is_processing', sa.BOOLEAN(),
    #                                    autoincrement=False, nullable=False))
    # op.add_column('dataset', sa.Column('is_active', sa.BOOLEAN(),
    #                                    autoincrement=False, nullable=False))
    # op.drop_column('dataset', 'processing')
    # op.drop_column('dataset', 'active')
    # ### end Alembic commands ###
    op.alter_column('dataset', 'active', new_column_name='is_active')
    op.alter_column('dataset', 'processing', new_column_name='is_processing')
