"""empty message

Revision ID: 657ec5b7d604
Revises: a71be3fc36bb
Create Date: 2019-02-05 12:56:52.043384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657ec5b7d604'
down_revision = 'a71be3fc36bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'is_processing_staging')
    op.drop_column('dataset', 'is_active_staging')
    op.drop_column('dataset', 'is_processing_production')
    op.drop_column('dataset', 'is_active_production')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('is_active_production', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('dataset', sa.Column('is_processing_production', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('dataset', sa.Column('is_active_staging', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('dataset', sa.Column('is_processing_staging', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
