"""empty message

Revision ID: 895b8fb5c847
Revises: 
Create Date: 2019-02-04 11:23:24.337183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895b8fb5c847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('dataset', sa.Column('is_processing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'is_processing')
    op.drop_column('dataset', 'is_active')
    # ### end Alembic commands ###
