"""empty message

Revision ID: a71be3fc36bb
Revises: 68a452d84872
Create Date: 2019-02-04 11:58:24.471682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a71be3fc36bb'
down_revision = '68a452d84872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'version_number',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'version_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
